<% app_name = 'shirt_app' %>

development:
  adapter: postgresql
  database: shirt_app_development

test:
  adapter: postgresql
  database: shirt_app_test

production:
  adapter: postgresql
  database: shirt_app_production
